### ISSUE TITLE
Use of richtext editor instead of legacy markdown editor.

### ISSUE THREAD

**Issue by buddh4** [humhub/meeting-issues#10]

**Comment by yurabakhtin** [comment]
@luke- MR https://git.humhub.org/modules/meeting/-/merge_requests/3

**Comment by luke-** [comment]
@yurabakhtin Looks fine, but it seems to not correctly handle uploaded files. The mapping is not set.

![image](https://user-images.githubusercontent.com/4736168/108694304-29b2d380-74ff-11eb-9a5d-0c28ef3f432d.png)

**Comment by buddh4** [comment]
@yurabakhtin before saving call `RichText::postProcess($text, $record)`

**Comment by yurabakhtin** [comment]
@buddh4 Thanks, @luke- Fixed in commit https://git.humhub.org/modules/meeting/-/merge_requests/3/diffs?commit_id=588c3b6a4992488246b46daa1802400b74cc91a8
