### ISSUE TITLE
Modules 1.7 Migration - Wall Stream Layouts

### ISSUE THREAD

**Issue by luke-** [humhub/meeting-issues#17]

**Comment by buddh4** [comment]
Here a first version, definetly needs some design concepts:

![grafik](https://user-images.githubusercontent.com/9800854/96730646-b49b8a00-13b6-11eb-887c-209a8393ea6d.png)

**Comment by buddh4** [comment]
The location is not required, so if not given only the date is visible ;/

**Comment by luke-** [comment]
@buddh4 Are there any other fields e.g. Description?

**Comment by buddh4** [comment]
These are the base information:

![grafik](https://user-images.githubusercontent.com/9800854/96746176-34315500-13c7-11eb-9c70-a8c5cd51a601.png)

Other than that we have Agenda items and optional a related task. Maybe we could add a short description, but it would also be optional.

**Comment by luke-** [comment]
Maybe we could include a Partiicpant List.

**Comment by buddh4** [comment]
I'd probably rather add the agenda titles as list or something? Perhaps also a link like "x people participate" also we have moderators for each agenda entry. Maybe we should wait for a concept by angie?

**Comment by luke-** [comment]
I would prefer a simple solution without Angie for now.
 It will take some time until Angie comes to a concept for this module.

**Comment by luke-** [comment]
@buddh4 Can you please publish a 1.7 compat version
