### ISSUE TITLE
ICS export leads to error page

### ISSUE THREAD

**Issue by Semir1212** [humhub/meeting-issues#21]
HH 1.7.1
Meetings

Share Meeting --> Export ICS

yii\base\UnknownPropertyException: Getting unknown property: humhub\modules\content\models\Content::user in /srv/humhub/protected/vendor/yiisoft/yii2/base/Component.php:154 Stack trace: #0 /srv/humhub/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(298): yii\base\Component->__get('user') #1 /srv/www/htdocs/doku2/modules/meeting/views/index/getICS.php(13): yii\db\BaseActiveRecord->__get('user') #2 /srv/humhub/protected/vendor/yiisoft/yii2/base/View.php(348): require('/srv/www/htdocs...') #3 /srv/humhub/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/srv/www/htdocs...', Array) #4 /srv/humhub/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/srv/www/htdocs...', Array, Object(humhub\modules\meeting\controllers\IndexController)) #5 /srv/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(440): yii\base\View->render('getICS', Array, Object(humhub\modules\meeting\controllers\IndexController)) #6 /srv/www/htdocs/doku2/modules/meeting/controllers/IndexController.php(230): yii\base\Controller->renderPartial('getICS', Array) #7 [internal function]: humhub\modules\meeting\controllers\IndexController->actionGetIcs('25', 'private') #8 /srv/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #9 /srv/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array) #10 /srv/humhub/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('get-ics', Array) #11 /srv/humhub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('meeting/index/g...', Array) #12 /srv/humhub/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request)) #13 /srv/www/htdocs/doku2/index.php(30): yii\base\Application->run() #14 {main}

**Comment by buddh4** [comment]
Seems to be fixed already.
