### ISSUE TITLE
Cannot validate date format

### ISSUE THREAD

**Issue by luke-** [humhub/meeting-issues#23]
- Switch language to "de"
- Go Administration -> Settings -> Appearenace -> Date Input Format and set to fixed format
![image](https://user-images.githubusercontent.com/4736168/107208665-36650100-6a02-11eb-9d53-8dad09481348.png)
- Try to create a new Meeting

**Comment by yurabakhtin** [comment]
@luke- MR https://git.humhub.org/modules/meeting/-/merge_requests/2
