### ISSUE TITLE
Filter form inside space shows JSON Response when hitting enter

### ISSUE THREAD

**Issue by siwa-tkapplmueller** [humhub/meeting-issues#29]
When the Meeting-Filter form inside a space is submitted (e.g. by hitting the enter key) the filter action is called directly instead of making an ajax call. That leads to the JSON Response being visible to the user.

The submit event should probably be handled exactly like keyup in this case.

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/meeting/pull/4.

**Comment by luke-** [comment]
@yurabakhtin Thanks
@siwa-tkapplmueller Will be fixed with the next release.
