### ISSUE TITLE
Concatenated search attributes reduces search effectiveness

### ISSUE THREAD

**Issue by verement** [humhub/meeting-issues#30]
The `itemTitles` and `itemNotes` search attributes are just concatenations without any separator, reducing the effectiveness of searches.

For example, a meeting with items “First” and “Second” will result in an `itemTitles` attribute of “FirstSecond” which is not ideal when using a custom search engine that tokenizes words or employs language analysis.

**Comment by Soundwave2142** [comment]
https://github.com/humhub/meeting/pull/15
