### ISSUE TITLE
Agenda Item/Entry - Send as a Message ERROR

### ISSUE THREAD

**Issue by mbumpalumpa** [humhub/meeting-issues#34]
When trying to send an Agenda Item/Entry as a message from the dropdown, an error occurs.

HH Version: 1.15.4
Module Version: 0.7.2

https://github.com/humhub/meeting-issues/assets/92554196/6e0e3e70-c825-4014-8593-e02bb5d51886

<details>
<summary><b>TOAST ERROR<b></summary>
</br>
<pre>
{
    "url": "/s/healthcare-initiatives/meeting/item/send?id=5",
    "status": 500,
    "response": {
        "error": true,
        "message": "An internal server error occurred."
    },
    "textStatus": "error",
    "xhr": {
        "readyState": 4,
        "responseText": "{\"error\":true,\"message\":\"An internal server error occurred.\"}",
        "responseJSON": {
            "error": true,
            "message": "An internal server error occurred."
        },
        "status": 500,
        "statusText": "Internal Server Error"
    },
    "dataType": "json",
    "error": true,
    "message": "An internal server error occurred.",
    "errorThrown": "Internal Server Error",
    "validationError": false
}
</pre>
</details>

<details>
<summary><b>LOG: INFO - Application</b></summary>
</br>
<pre>
$_GET = [
'id' => '5'
'cguid' => '9fe3b1be-028a-4e41-b97a-ac20070039cd'
]

$_SERVER = [
'REDIRECT_STATUS' => '200'
'HTTP_X_REAL_IP' => '95.XXX.XXX.XX'
'HTTP_X_FORWARDED_FOR' => '95.XXX.XXX.XX'
'HTTP_X_FORWARDED_PROTO' => 'https'
'HTTP_HOST' => 'ahrad.humhub.com'
'HTTP_X_FORWARDED_HOST' => 'ahrad.humhub.com'
'HTTP_CONNECTION' => 'close'
'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:124.0) Gecko/20100101 Firefox/124.0'
'HTTP_ACCEPT' => '*/*'
'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.5'
'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br'
'HTTP_REFERER' => 'https://ahrad.humhub.com/s/healthcare-initiatives/meeting/index/view?id=1'
'HTTP_X_CSRF_TOKEN' => 'DOTpmzCaPBxTk9e9Ote2AbkJkQm854JXp3wk9l-ahbtWhdHXB88RczT9mtwKgdRt8iTafNfV4wHTMEWhGuPazQ=='
'HTTP_HUMHUB_VIEW_CONTEXT' => 'modal'
'HTTP_X_REQUESTED_WITH' => 'XMLHttpRequest'
'HTTP_SEC_FETCH_DEST' => 'empty'
'HTTP_SEC_FETCH_MODE' => 'cors'
'HTTP_SEC_FETCH_SITE' => 'same-origin'
'HTTP_COOKIE' => 'PHPSESSID=mjfrg1b2hl0gngiif4vcvlk2og; _csrf=f1c64442fa3db2c2a0566f9d5fdb3a256b3df4792419b33e661e88340a4a2701a%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22Za8L7U-ognMa0VblK-Kuk2aVtLaWEy_v%22%3B%7D; language=e2468f5e6a1946b588cf054d0d3f35307420454c3759a90d99d71fd607171b56a%3A2%3A%7Bi%3A0%3Bs%3A8%3A%22language%22%3Bi%3A1%3Bs%3A5%3A%22en-US%22%3B%7D; _identity=7eca414e0af65cc99632746c25ce82c5146e664e304bac17904f8dad1010e514a%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A46%3A%22%5B1%2C%22j_wFeuiWyC0cc4ZRHoslvzrtV4Qq6vC_%22%2C2592000%5D%22%3B%7D'
'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
'SERVER_SIGNATURE' => ''
'SERVER_SOFTWARE' => 'Apache'
'SERVER_NAME' => 'ahrad.humhub.com'
'SERVER_ADDR' => '2a01:4f8:1c17:fe1f::1'
'SERVER_PORT' => 443
'REMOTE_ADDR' => '2a01:4f8:c012:ed58::1'
'DOCUMENT_ROOT' => '/srv/www/htdocs/ahrad'
'REQUEST_SCHEME' => 'https'
'CONTEXT_PREFIX' => ''
'CONTEXT_DOCUMENT_ROOT' => '/srv/www/htdocs/ahrad'
'SERVER_ADMIN' => 'webmaster@humhub.com'
'SCRIPT_FILENAME' => '/srv/www/htdocs/ahrad/index.php'
'REMOTE_PORT' => '54706'
'REDIRECT_URL' => '/s/healthcare-initiatives/meeting/item/send'
'REDIRECT_QUERY_STRING' => 'id=5'
'GATEWAY_INTERFACE' => 'CGI/1.1'
'SERVER_PROTOCOL' => 'HTTP/1.0'
'REQUEST_METHOD' => 'GET'
'QUERY_STRING' => 'id=5'
'REQUEST_URI' => '/s/healthcare-initiatives/meeting/item/send?id=5'
'SCRIPT_NAME' => '/index.php'
'PHP_SELF' => '/index.php'
'REQUEST_TIME_FLOAT' => 1713356816.6253
'REQUEST_TIME' => 1713356816
] 
</pre>
</details>

<details>
<summary><b>LOG: ERROR - yii\base\ErrorException:2<b></summary>
</br>
<pre>
yii\base\ErrorException: Undefined variable $fileHandlers in /srv/www/htdocs/ahrad/modules/mail/views/mail/create.php:63
Stack trace:
#0 /srv/www/htdocs/ahrad/modules/mail/views/mail/create.php(63): yii\base\ErrorHandler->handleError()
#1 /srv/humhub/protected/vendor/yiisoft/yii2/base/View.php(347): require('...')
#2 /srv/humhub/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile()
#3 /srv/humhub/protected/humhub/modules/ui/view/components/View.php(240): yii\base\View->renderFile()
#4 /srv/humhub/protected/vendor/yiisoft/yii2/web/Controller.php(50): humhub\modules\ui\view\components\View->renderAjax()
#5 /srv/www/htdocs/ahrad/modules/meeting/controllers/ItemController.php(147): yii\web\Controller->renderAjax()
#6 [internal function]: humhub\modules\meeting\controllers\ItemController->actionSend()
#7 /srv/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#8 /srv/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#9 /srv/humhub/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#10 /srv/humhub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#11 /srv/humhub/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#12 /srv/www/htdocs/ahrad/index.php(24): yii\base\Application->run()
#13 {main} 
</pre>
</details>

**Console**
[console-export-2024-4-19_17-1-38.txt](https://github.com/humhub/meeting-issues/files/15042202/console-export-2024-4-19_17-1-38.txt)
[console-export-2024-4-19_17-1-21.txt](https://github.com/humhub/meeting-issues/files/15042204/console-export-2024-4-19_17-1-21.txt)

**Comment by yurabakhtin** [comment]
@mbumpalumpa Thanks, it was broken after updating of the "Message" module here https://github.com/humhub/mail/commit/b55d41d0f8415219ff394ca390c24b7cac44a717.
@luke- Fixed in PR https://github.com/humhub/meeting/pull/35.

**Comment by luke-** [comment]
Fixed in 0.7.3
