### ISSUE TITLE
Use CSS variables

### ISSUE THREAD

**Issue by felixhahnweilheim** [humhub/meeting-issues#35]
For better compatibility (with dark mode and custom themes) the module should use CSS variables instead of hard-coded colors.

Original issue: https://community.humhub.com/content/perma?id=281403

Most important lines:

```
.meeting-overview .meeting-filter {
    background-color:#f7f7f7;
}
#meeting-container .panel-heading {
    background-color: #f7f7f7;
 }
```
Those lines should use `var(--background-color-secondary)` (which is `#f9f9f9` in the standard theme).

I can also correct the whole LESS file and post it here if prefered.

**Comment by marc-farre** [comment]
@felixhahnweilheim Thanks for offering to update the LESS file!

This is the current version: [meeting.zip](https://github.com/user-attachments/files/17339350/meeting.zip)

If you send it back here, I'll create a PR and @luke- will release a new version of the module.

**Comment by felixhahnweilheim** [comment]
[meeting.zip](https://github.com/user-attachments/files/17339998/meeting.zip)

Thanks Marc!

**Comment by marc-farre** [comment]
@felixhahnweilheim Thanks!

@luke- PR https://github.com/humhub/meeting/pull/51
