### ISSUE TITLE
Can't create meeting when using Swedish locale

### ISSUE THREAD

**Issue by tyte** [humhub/meeting-issues#6]
When I try to create a meeting using Swedish locale, it simply doesn't work. When I switch to english, everything is just fine. 

I guess it might be related to issues in calendar module as well:
https://github.com/humhub/humhub-modules-calendar/issues/106
https://github.com/humhub/humhub-modules-calendar/issues/146

**Comment by buddh4** [comment]
There is a new meeting module version available, which should fix the issue.
