### ISSUE TITLE
License key doesn't work anymore

### ISSUE THREAD

**Issue by tyte** [humhub/meeting-issues#7]
I purchased meetings plugin in december. It was disabled and uninstalled for some time (there were some technical problems that needed to be solved, like https://github.com/humhub/humhub-modules-meetings/issues/6) and now I would like to reinstall and enable it again. But the license key doesn't work anymore. 

It's exactly the same site and I assume that the license should work. Or?...

**Comment by luke-** [comment]
Please contact our support at hello@humhub.com.

Normally the license key is not deactivated and can be activated again under Administration -> Modules -> Purchases.
