### ISSUE TITLE
Times are messed up

### ISSUE THREAD

**Issue by arttu-uusikyyny** [humhub/meeting-issues#8]
Hello, I have problem with times. When I create meeting I put example start time to 18 clock. But when the meetings created it shows start time at 17?
![Sieppaa](https://user-images.githubusercontent.com/35232544/76765758-983fcb00-679f-11ea-8c1c-9019161ad453.JPG)

When created:
![fchgxn](https://user-images.githubusercontent.com/35232544/76765772-9c6be880-679f-11ea-9bf9-7351c89cde73.JPG)

**Comment by luke-** [comment]
Did you set different time zones for the server (Administration -> Settings) and user profile (User -> Settings)?

**Comment by arttu-uusikyyny** [comment]
Yes i have -7 UTC Administration -> Settings 
And users have UTC +2

**Comment by luke-** [comment]
What happens if you create a normal post?
Is the creation time correct there?

**Comment by arttu-uusikyyny** [comment]
No it shows as normal. I live in time zone utc +2. I think that my servers time zone is utc -7. Becouse if i put Administration -> Settings to same (utc +2) all post show up to be posted 9 hours ago.

**Comment by arttu-uusikyyny** [comment]
![image](https://user-images.githubusercontent.com/35232544/77088641-6b90eb00-6a0d-11ea-9f6c-c57981fbca20.png)

In calendar marking it show normal time.

**Comment by luke-** [comment]
What about the creation date of regular posts?
 e.g.
![scrn-2020-03-20-20-41-59](https://user-images.githubusercontent.com/4736168/77200789-93ef1700-6aeb-11ea-9572-21288175d9bf.png)

**Comment by arttu-uusikyyny** [comment]
Yes it shows right time. If create post ”one minute ago”

**Comment by luke-** [comment]
@buddh4 any idea?

**Comment by buddh4** [comment]
I found an issue with the timezone picker, but this should not affect meetings created in user timezone. There is a new version available which fixes this issue. Can you do another test with the latest module version?
